name: Fetch Scopus Papers Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st day of every month
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  fetch-papers:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the fetchPapers.js script
      - name: Run Scopus fetcher script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          ELSEVIER_API_KEY: ${{ secrets.ELSEVIER_API_KEY }}
        run: npm start
